name: Build QMK firmware
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "QMK firmware branch/tag to build against"
        required: true
        default: "master"

jobs:
  build:
    name: QMK Userspace Build
    uses: qmk/qmk_userspace/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: ${{ github.event.inputs.branch || 'master' }}

  publish:
    name: Publish artifacts
    needs: build
    uses: qmk/qmk_userspace/.github/workflows/qmk_userspace_publish.yml@main
